### ISSUE TITLE
I get this error on Version 4.0.0 and above.

### ISSUE THREAD

**Issue by mucahitsimsek** [VB10/vexana#95]
![image](https://github.com/VB10/vexana/assets/46285187/c39ed595-b504-4832-8861-e2cd9b88ba34)

**Comment by mucahitsimsek** [comment]
And in 3.5.4 there is no error model handle.

https://stackoverflow.com/questions/78243612/while-using-the-vexana-package-in-flutter-i-create-my-own-error-model-but-i-am

**Comment by behzodfaiziev** [comment]
@mucahitsimsek is this issue still persisting? Did you try to update flutter version

**Comment by mucahitsimsek** [comment]
@behzodfaiziev Hi, I edited the bug using version 3.5.4. Here's what I've done before:
	rm -rf pubspec.lock
	rm -rf 
	flutter clean
	get flutter pub
ios/Podfile.lock	
	cd ios && pod cache clean --all
	cd ios && pod repo update
	cd ios && pod install

Even though I updated the build files, I could not use the version I specified. I have not updated the version since Mar 29.

**Comment by behzodfaiziev** [comment]
> And in 3.5.4 there is no error model handle.
> 
> https://stackoverflow.com/questions/78243612/while-using-the-vexana-package-in-flutter-i-create-my-own-error-model-but-i-am

In here it seems that issue is removed from stackoverflow. 

### As I assume, you
- run latest flutter version (<=3.22.2)
- vexana (4.0.0)
- os: iOS

Does this error cause issue to run iOS app? 
Can you try to uninstall Flutter sdk and install again? Sometimes there might be issues in local flutter sdk
Also you can try:
`flutter clean && flutter pub get && cd ios && pod install --repo-update && cd ..`
